### PR TITLE
Integrate Mayhem

### PR DESCRIPTION
**Pull request by 4812571**

### CODE REVIEW

**Comment by jhersack** [comment]
I'm not seeing any runs for the new mayhem files on https://mayhem.forallsecure.com/4812571/formats. Please execute some runs so we can score the submission.

**Comment by 4812571** [comment]
I just ran a run! Sorry about that, it appears uploading the SARIF file got rate-limited last time @Jon-FAS

**Comment by jhersack** [comment]
Awesome. I'll take a look at it and get it processed. Thanks!

**Comment by jhersack** [comment]
@4812571, it looks like your permissions aren't set correctly for the repo. It's not running the new workflow correctly. I'm not seeing the new targets and there's an error in your actions logfile.

**Pull request merged**
